'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ApiClient } from '@/lib/api-client';

export default function NewAdminSupplierPage() {
  const router = useRouter(); const [companyName, setCompanyName] = useState(''); const [country, setCountry] = useState(''); const [contactEmail, setContactEmail] = useState(''); const [contactPhone, setContactPhone] = useState(''); const [error, setError] = useState(''); const [isSaving, setIsSaving] = useState(false);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setIsSaving(true); try { await ApiClient.createAdminSupplier({ companyName: companyName.trim(), country: country.trim(), contactEmail: contactEmail.trim(), ...(contactPhone.trim() ? { contactPhone: contactPhone.trim() } : {}) }); router.push('/admin/suppliers'); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : 'Failed to create supplier.'); } finally { setIsSaving(false); } };
  const inputClass = 'w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500';
  return <div className="max-w-xl"><Link href="/admin/suppliers" className="inline-flex text-sm text-slate-400 hover:text-blue-500 mb-6">← Back to suppliers</Link><h1 className="text-2xl font-bold text-slate-800 mb-2">New supplier</h1><p className="text-sm text-slate-400 mb-8">Add a supplier contact for product assignment.</p><form onSubmit={save} className="rounded-xl border border-slate-200 bg-white p-6 space-y-5">{error && <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<div><label className="block text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1.5">Company name *</label><input required value={companyName} onChange={(event) => setCompanyName(event.target.value)} className={inputClass} /></div><div><label className="block text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1.5">Country *</label><input required value={country} onChange={(event) => setCountry(event.target.value)} className={inputClass} /></div><div><label className="block text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1.5">Contact email *</label><input required type="email" value={contactEmail} onChange={(event) => setContactEmail(event.target.value)} className={inputClass} /></div><div><label className="block text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1.5">Contact phone</label><input value={contactPhone} onChange={(event) => setContactPhone(event.target.value)} className={inputClass} /></div><div className="flex gap-3"><button disabled={isSaving} className="px-4 py-2 rounded-lg bg-blue-500 text-white text-sm font-semibold disabled:opacity-50 cursor-pointer">{isSaving ? 'Creating...' : 'Create supplier'}</button><Link href="/admin/suppliers" className="px-4 py-2 rounded-lg border border-slate-200 text-sm text-slate-600">Cancel</Link></div></form></div>;
}
