'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import { ApiClient } from '@/lib/api-client';

export default function EditAdminSupplierPage() {
  const params = useParams(); const router = useRouter(); const id = params.id as string;
  const [companyName, setCompanyName] = useState(''); const [country, setCountry] = useState(''); const [contactEmail, setContactEmail] = useState(''); const [contactPhone, setContactPhone] = useState(''); const [error, setError] = useState(''); const [isLoading, setIsLoading] = useState(true); const [isSaving, setIsSaving] = useState(false);
  useEffect(() => { ApiClient.getAdminSupplierById(id).then((supplier) => { setCompanyName(supplier.companyName); setCountry(supplier.country); setContactEmail(supplier.contactEmail); setContactPhone(supplier.contactPhone || ''); }).catch((loadError) => setError(loadError instanceof Error ? loadError.message : 'Failed to load supplier.')).finally(() => setIsLoading(false)); }, [id]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setIsSaving(true); try { await ApiClient.updateAdminSupplier(id, { companyName: companyName.trim(), country: country.trim(), contactEmail: contactEmail.trim(), contactPhone: contactPhone.trim() || undefined }); router.push(`/admin/suppliers/${id}`); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : 'Failed to update supplier.'); } finally { setIsSaving(false); } };
  const inputClass = 'w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500';
  if (isLoading) return <p className="text-sm text-slate-400">Loading supplier...</p>;
  return <div className="max-w-xl"><Link href={`/admin/suppliers/${id}`} className="inline-flex text-sm text-slate-400 hover:text-blue-500 mb-6">← Back to supplier</Link><h1 className="text-2xl font-bold text-slate-800 mb-8">Edit supplier</h1><form onSubmit={save} className="rounded-xl border border-slate-200 bg-white p-6 space-y-5">{error && <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<div><label className="block text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1.5">Company name *</label><input required value={companyName} onChange={(event) => setCompanyName(event.target.value)} className={inputClass} /></div><div><label className="block text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1.5">Country *</label><input required value={country} onChange={(event) => setCountry(event.target.value)} className={inputClass} /></div><div><label className="block text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1.5">Contact email *</label><input required type="email" value={contactEmail} onChange={(event) => setContactEmail(event.target.value)} className={inputClass} /></div><div><label className="block text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1.5">Contact phone</label><input value={contactPhone} onChange={(event) => setContactPhone(event.target.value)} className={inputClass} /></div><div className="flex gap-3"><button disabled={isSaving} className="px-4 py-2 rounded-lg bg-blue-500 text-white text-sm font-semibold disabled:opacity-50 cursor-pointer">{isSaving ? 'Saving...' : 'Save changes'}</button><Link href={`/admin/suppliers/${id}`} className="px-4 py-2 rounded-lg border border-slate-200 text-sm text-slate-600">Cancel</Link></div></form></div>;
}
